# EXERCICI 1

In [3]:
import pandas as pd
import numpy as np

#descarrega dataframe DelayedFlights

ret = pd.read_csv('DelayedFlights.csv')
ret.head(13) #mostra les 13 primeres files, per fer una criba de les columnes a triar

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0
10,17,2008,1,3,4,754.0,745,940.0,955,WN,...,5.0,16.0,0,N,0,NaN,NaN,NaN,NaN,NaN
11,18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,...,4.0,9.0,0,N,0,0.0,0.0,0.0,0.0,16.0
12,19,2008,1,3,4,1416.0,1325,1512.0,1435,WN,...,2.0,5.0,0,N,0,12.0,0.0,0.0,0.0,25.0

In [5]:
ret.info() #info del dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [6]:
ret.shape #número de files i columnes totals del dataframe

(1936758, 30)

In [7]:
ret.columns #columnes del dataframe

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [9]:
# tria columnes necessàries

# eliminació any: valor no útil per analisi, totes les dades són del 2008.
# justificació tria mesos i dies mes i setmana: analitzar si retards es donen en mesos i/o dies mes concrets.
# justificació temps dep, arr i altres: anàlisi de minimització de retard durant el vol, o altres.
# eliminació FlightNumnúmero: valor no útil per anàlisi.
# justificació Origin, Dest, Distance: anàlisi retards i distàncies.
# eliminació TaxiIn, TaxiOut: desconeixement del valor
# justificació TailNum: anàlisi avió que acumula més retards.
# eliminació Cancelled, CancellationCode, Diverted: valors no vàlids per anàlisi de retards.
# justificació CarrierDelay, WeatherDelay, NASDelay', SecurityDelay, LateAircraftDelay: anàlisi motiu retard.


lessret = ret[['Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay', 'DepDelay', 'Origin', 'Dest', 'Distance', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']]
lessret

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,TailNum,ActualElapsedTime,...,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,3,4,2003.0,1955,2211.0,2225,WN,N712SW,128.0,...,-14.0,8.0,IAD,TPA,810,NaN,NaN,NaN,NaN,NaN
1,1,3,4,754.0,735,1002.0,1000,WN,N772SW,128.0,...,2.0,19.0,IAD,TPA,810,NaN,NaN,NaN,NaN,NaN
2,1,3,4,628.0,620,804.0,750,WN,N428WN,96.0,...,14.0,8.0,IND,BWI,515,NaN,NaN,NaN,NaN,NaN
3,1,3,4,1829.0,1755,1959.0,1925,WN,N464WN,90.0,...,34.0,34.0,IND,BWI,515,2.0,0.0,0.0,0.0,32.0
4,1,3,4,1940.0,1915,2121.0,2110,WN,N726SW,101.0,...,11.0,25.0,IND,JAX,688,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,12,13,6,1250.0,1220,1617.0,1552,DL,N938DL,147.0,...,25.0,30.0,MSP,ATL,906,3.0,0.0,0.0,0.0,22.0
1936754,12,13,6,657.0,600,904.0,749,DL,N3743H,127.0,...,75.0,57.0,RIC,ATL,481,0.0,57.0,18.0,0.0,0.0
1936755,12,13,6,1007.0,847,1149.0,1010,DL,N909DA,162.0,...,99.0,80.0,ATL,IAH,689,1.0,0.0,19.0,0.0,79.0
1936756,12,13,6,1251.0,1240,1446.0,1437,DL,N646DL,115.0,...,9.0,11.0,IAD,ATL,533,NaN,NaN,NaN,NaN,NaN
1936757,12,13,6,1110.0,1103,1413.0,1418,DL,N908DL,123.0,...,-5.0,7.0,SAT,ATL,874,NaN,NaN,NaN,NaN,NaN

In [10]:
#triar 200000 valors aleatoriament

retard = lessret.sample(n = 200000).reset_index(drop=True) 
retard

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,TailNum,ActualElapsedTime,...,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,7,20,7,1441.0,1420,1753.0,1720,MQ,N621AE,132.0,...,33.0,21.0,ORD,RIC,642,0.0,0.0,12.0,0.0,21.0
1,8,9,6,1640.0,1610,1932.0,1910,9E,80209E,172.0,...,22.0,30.0,FLL,IND,1005,0.0,0.0,0.0,0.0,22.0
2,2,13,3,2125.0,2105,2233.0,2159,OH,N391CA,128.0,...,34.0,20.0,CVG,MSP,596,0.0,20.0,14.0,0.0,0.0
3,7,7,1,2036.0,2020,2203.0,2150,MQ,N614AE,87.0,...,13.0,16.0,DFW,GPT,500,NaN,NaN,NaN,NaN,NaN
4,10,22,3,1448.0,1340,1845.0,1732,XE,N13161,177.0,...,73.0,68.0,MEM,EWR,946,0.0,0.0,73.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1,3,4,1538.0,1455,1640.0,1612,XE,N11194,62.0,...,28.0,43.0,OKC,AUS,358,5.0,0.0,0.0,0.0,23.0
199996,6,9,1,1725.0,1540,121.0,2357,UA,N590UA,296.0,...,84.0,105.0,OGG,LAX,2486,0.0,0.0,0.0,0.0,84.0
199997,7,25,5,1128.0,855,1328.0,1110,B6,N563JB,120.0,...,138.0,153.0,IAD,MCO,758,138.0,0.0,0.0,0.0,0.0
199998,6,15,7,15.0,2230,749.0,545,FL,N279AT,274.0,...,124.0,105.0,LAX,ATL,1946,0.0,0.0,19.0,0.0,105.0
199999,7,12,6,2000.0,1945,2114.0,2107,B6,N249JB,74.0,...,7.0,15.0,BUF,BOS,396,NaN,NaN,NaN,NaN,NaN

In [12]:
retard.shape

(200000, 22)

# EXERCICI 2

In [13]:
retard.info() #informacio del dataset retard i columnes d'interés

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 22 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Month              200000 non-null  int64
 1   DayofMonth         200000 non-null  int64
 2   DayOfWeek          200000 non-null  int64
 3   DepTime            200000 non-null  float64
 4   CRSDepTime         200000 non-null  int64
 5   ArrTime            199253 non-null  float64
 6   CRSArrTime         200000 non-null  int64
 7   UniqueCarrier      200000 non-null  object
 8   TailNum            199999 non-null  object
 9   ActualElapsedTime  199114 non-null  float64
 10  CRSElapsedTime     199983 non-null  float64
 11  AirTime            199114 non-null  float64
 12  ArrDelay           199114 non-null  float64
 13  DepDelay           200000 non-null  float64
 14  Origin             200000 non-null  object
 15  Dest               200000 non-null  object
 16  Distance           200000 non-null  int64
 17  CarrierDelay       128852 non-null  float64
 18  WeatherDelay       128852 non-null  float64
 19  NASDelay           128852 non-null  float64
 20  SecurityDelay      128852 non-null  float64
 21  LateAircraftDelay  128852 non-null  float64
dtypes: float64(12), int64(6), object(4)
memory usage: 33.6+ MB

In [14]:
retard.describe() #resum estadístic del dataset retard

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,199253.000000,200000.000000,199114.000000,199983.000000,199114.000000,199114.000000,200000.000000,200000.000000,128852.000000,128852.000000,128852.000000,128852.000000,128852.000000
mean,6.105875,15.769845,3.978720,1518.095640,1467.084240,1610.171691,1633.369775,133.578754,134.562513,108.557434,42.180836,43.190200,767.416900,19.030034,3.799537,14.967148,0.092385,25.364798
std,3.484805,8.770951,1.997262,450.723353,424.765408,547.925886,464.917136,72.132035,71.424657,68.674531,56.660249,53.429251,574.516657,42.975703,21.782002,33.961935,1.860157,42.222255
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,18.000000,-18.000000,0.000000,-69.000000,6.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,8.000000,2.000000,1202.000000,1135.000000,1315.000000,1325.000000,80.000000,82.000000,58.000000,9.000000,12.000000,340.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6.000000,16.000000,4.000000,1545.000000,1510.000000,1715.000000,1705.000000,116.000000,117.000000,90.000000,24.000000,24.000000,609.000000,2.000000,0.000000,2.000000,0.000000,8.000000
75%,9.000000,23.000000,6.000000,1900.000000,1815.000000,2031.000000,2014.250000,165.000000,165.000000,138.000000,56.000000,53.000000,1003.000000,21.000000,0.000000,15.000000,0.000000,34.000000
max,12.000000,31.000000,7.000000,2400.000000,2359.000000,2400.000000,2400.000000,687.000000,660.000000,652.000000,1707.000000,1710.000000,4962.000000,1707.000000,1070.000000,1337.000000,141.000000,1303.000000

In [15]:
# resum estadístic columna retards.

retsor = retard['CRSDepTime'] #tria columna retard sortida
retsor.describe()

count    200000.000000
mean       1467.084240
std         424.765408
min           1.000000
25%        1135.000000
50%        1510.000000
75%        1815.000000
max        2359.000000
Name: CRSDepTime, dtype: float64

In [16]:
# resum estadístic columna retards arribada.

retarr = retard['CRSArrTime'] #tria columna retard arribada
retarr.describe()

count    200000.000000
mean       1633.369775
std         464.917136
min           0.000000
25%        1325.000000
50%        1705.000000
75%        2014.250000
max        2400.000000
Name: CRSArrTime, dtype: float64

In [17]:
# resum estadístic columna distància.

dista = retard['Distance'] #tria columna distància
dista.describe()

count    200000.000000
mean        767.416900
std         574.516657
min          31.000000
25%         340.000000
50%         609.000000
75%        1003.000000
max        4962.000000
Name: Distance, dtype: float64

In [13]:
# dades faltants per columna.

retard.isnull().sum() # número de nulls per columna

Month                    0
DayofMonth               0
DayOfWeek                0
DepTime                  0
CRSDepTime               0
ArrTime                742
CRSArrTime               0
UniqueCarrier            0
TailNum                  1
ActualElapsedTime      871
CRSElapsedTime          21
AirTime                871
ArrDelay               871
DepDelay                 0
Origin                   0
Dest                     0
Distance                 0
CarrierDelay         71131
WeatherDelay         71131
NASDelay             71131
SecurityDelay        71131
LateAircraftDelay    71131
dtype: int64

In [18]:
#càlcul velocitat mitja

dist = retard['Distance']
vel = retard['CRSElapsedTime']
vel_mitja = dist/vel

retard['vel_m'] = vel_mitja #afegim columna al dataframe retard
retard

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,TailNum,ActualElapsedTime,...,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,vel_m
0,7,20,7,1441.0,1420,1753.0,1720,MQ,N621AE,132.0,...,21.0,ORD,RIC,642,0.0,0.0,12.0,0.0,21.0,5.350000
1,8,9,6,1640.0,1610,1932.0,1910,9E,80209E,172.0,...,30.0,FLL,IND,1005,0.0,0.0,0.0,0.0,22.0,5.583333
2,2,13,3,2125.0,2105,2233.0,2159,OH,N391CA,128.0,...,20.0,CVG,MSP,596,0.0,20.0,14.0,0.0,0.0,5.228070
3,7,7,1,2036.0,2020,2203.0,2150,MQ,N614AE,87.0,...,16.0,DFW,GPT,500,NaN,NaN,NaN,NaN,NaN,5.555556
4,10,22,3,1448.0,1340,1845.0,1732,XE,N13161,177.0,...,68.0,MEM,EWR,946,0.0,0.0,73.0,0.0,0.0,5.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1,3,4,1538.0,1455,1640.0,1612,XE,N11194,62.0,...,43.0,OKC,AUS,358,5.0,0.0,0.0,0.0,23.0,4.649351
199996,6,9,1,1725.0,1540,121.0,2357,UA,N590UA,296.0,...,105.0,OGG,LAX,2486,0.0,0.0,0.0,0.0,84.0,7.842271
199997,7,25,5,1128.0,855,1328.0,1110,B6,N563JB,120.0,...,153.0,IAD,MCO,758,138.0,0.0,0.0,0.0,0.0,5.614815
199998,6,15,7,15.0,2230,749.0,545,FL,N279AT,274.0,...,105.0,LAX,ATL,1946,0.0,0.0,19.0,0.0,105.0,7.631373
199999,7,12,6,2000.0,1945,2114.0,2107,B6,N249JB,74.0,...,15.0,BUF,BOS,396,NaN,NaN,NaN,NaN,NaN,4.829268

In [19]:
# vol amb retard? si/no

# nova columna

def sn(x):
    for x in retard['CRSArrTime']:
        if x == retard['ArrTime']:
            print('NO retard') in ot
        else:
            print('YES retard') in ot
            
            ot = retard['vel_m']
            retard

# NO ENTENC????

In [20]:
retard['UniqueCarrier'] #aerolinees del dataframe

# taula aerolinies amb més retards

comp_ret = retard['UniqueCarrier'].value_counts()
comp_ret

WN    39041
AA    20006
MQ    14513
UA    14506
OO    13622
DL    12169
XE    10587
CO    10422
US    10245
EV     8597
NW     8195
FL     7257
YV     6779
B6     5645
OH     5340
9E     5294
AS     4048
F9     2901
HA      758
AQ       75
Name: UniqueCarrier, dtype: int64

In [21]:
#distancia més llarga

vols = retard.groupby('UniqueCarrier').count() #agrupació per vols
vols

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,TailNum,ActualElapsedTime,CRSElapsedTime,...,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,vel_m
UniqueCarrier,,,,,,,,,,,,,,,,,,,,,
9E,5294,5294,5294,5294,5294,5272,5294,5294,5266,5277,...,5294,5294,5294,5294,3646,3646,3646,3646,3646,5277
AA,20006,20006,20006,20006,20006,19921,20006,20006,19903,20006,...,20006,20006,20006,20006,13861,13861,13861,13861,13861,20006
AQ,75,75,75,75,75,73,75,75,73,75,...,75,75,75,75,36,36,36,36,36,75
AS,4048,4048,4048,4048,4048,4020,4048,4048,4017,4048,...,4048,4048,4048,4048,2452,2452,2452,2452,2452,4048
B6,5645,5645,5645,5645,5645,5623,5645,5645,5615,5645,...,5645,5645,5645,5645,3898,3898,3898,3898,3898,5645
CO,10422,10422,10422,10422,10422,10381,10422,10422,10372,10422,...,10422,10422,10422,10422,6043,6043,6043,6043,6043,10422
DL,12169,12169,12169,12169,12169,12115,12169,12169,12108,12169,...,12169,12169,12169,12169,7702,7702,7702,7702,7702,12169
EV,8597,8597,8597,8597,8597,8591,8597,8597,8587,8597,...,8597,8597,8597,8597,6027,6027,6027,6027,6027,8597
F9,2901,2901,2901,2901,2901,2893,2901,2901,2893,2901,...,2901,2901,2901,2901,1669,1669,1669,1669,1669,2901
FL,7257,7257,7257,7257,7257,7231,7257,7257,7230,7257,...,7257,7257,7257,7257,4794,4794,4794,4794,4794,7257
HA,758,758,758,758,758,758,758,758,758,758,...,758,758,758,758,445,445,445,445,445,758
MQ,14513,14513,14513,14513,14513,14457,14513,14513,14447,14513,...,14513,14513,14513,14513,10007,10007,10007,10007,10007,14513
NW,8195,8195,8195,8195,8195,8175,8195,8195,8168,8195,...,8195,8195,8195,8195,5695,5695,5695,5695,5695,8195
OH,5340,5340,5340,5340,5340,5320,5340,5339,5314,5340,...,5340,5340,5340,5340,4040,4040,4040,4040,4040,5340
OO,13622,13622,13622,13622,13622,13549,13622,13622,13541,13622,...,13622,13622,13622,13622,9066,9066,9066,9066,9066,13622
UA,14506,14506,14506,14506,14506,14456,14506,14506,14444,14506,...,14506,14506,14506,14506,9831,9831,9831,9831,9831,14506
US,10245,10245,10245,10245,10245,10206,10245,10245,10201,10245,...,10245,10245,10245,10245,6215,6215,6215,6215,6215,10245
WN,39041,39041,39041,39041,39041,38928,39041,39041,38907,39041,...,39041,39041,39041,39041,20962,20962,20962,20962,20962,39041
XE,10587,10587,10587,10587,10587,10545,10587,10587,10535,10587,...,10587,10587,10587,10587,7326,7326,7326,7326,7326,10587
YV,6779,6779,6779,6779,6779,6739,6779,6779,6735,6779,...,6779,6779,6779,6779,5137,5137,5137,5137,5137,6779

In [22]:
# vols mes llargs

mes_temps = retard['ActualElapsedTime']
max_temps = mes_temps.max() # màxim temps de vol
max_temps

687.0

In [23]:
# vol més endarrerit

mes_retard = retard['ArrDelay']
max_retard = mes_retard.max() #màxim retard
max_retard

1707.0

In [24]:
# distància més llarga

mes_dist = retard['Distance']
max_dist = mes_dist.max() #màxima distància
max_dist

4962

# EXERCICI 3

In [25]:
pip install openpyxl

Requirement already satisfied: openpyxl in ./opt/anaconda3/lib/python3.9/site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in ./opt/anaconda3/lib/python3.9/site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
# dataset retard a Excel

datatoexcel = pd.ExcelWriter('Retards.xlsx')
retard.to_excel(datatoexcel)
datatoexcel.save()